#!/bin/bash
PROJECT_ID="PVT_kwDOCtphAM4Ao7bH"
PROJECT_NUMBER=2
OWNER="LumiaEIP"
REPO="LumiaEIP/pre-prod"
STATUS_FIELD_ID="PVTSSF_lADOCtphAM4Ao7bHzgga4tw"

# Status Option IDs
TODO="f75ad846"
IN_PROGRESS="47fc9ee4"
CODE_REVIEW="a4934e36"
DELIVERED="98236657"

create_task() {
    local TITLE="$1"
    local STATUS_ID="$2"
    local BODY="$3"
    
    # Create issue and add to project in one go if possible, or sequentially
    # Using gh issue create first to get a real issue
    ISSUE_URL=$(gh issue create --repo "$REPO" --title "$TITLE" --body "$BODY" --json url --jq '.url')
    
    # Add to project
    ITEM_ID=$(gh project item-add "$PROJECT_NUMBER" --owner "$OWNER" --url "$ISSUE_URL" --format json --jq '.id')
    
    # Set status
    gh project item-edit --id "$ITEM_ID" --project-id "$PROJECT_ID" --field-id "$STATUS_FIELD_ID" --single-select-option-id "$STATUS_ID"
    
    echo "Created: $TITLE"
}

# --- GENERATED TASK LIST (200 tasks) ---
# I will use a loop with data to avoid a massive script file

declare -a tasks=(
# Delivered - Backend (50)
"[BACKEND] Initial Spring Boot project scaffolding|$DELIVERED|Setup Maven, dependencies and project structure."
"[BACKEND] MongoDB connection configuration|$DELIVERED|Setup MongoClient and Spring Data MongoDB properties."
"[BACKEND] User entity and repository implementation|$DELIVERED|Define User document and basic CRUD repository."
"[BACKEND] JWT Authentication provider setup|$DELIVERED|Implement token generation and validation logic."
"[BACKEND] SecurityConfig for API protection|$DELIVERED|Configure HttpSecurity and CORS for the backend."
"[BACKEND] UsersController: GET /users/me endpoint|$DELIVERED|Return authenticated user details."
"[BACKEND] UsersController: POST /users/register endpoint|$DELIVERED|Handle new user signup with validation."
"[BACKEND] UsersController: POST /users/login endpoint|$DELIVERED|Authenticate users and return JWT."
"[BACKEND] Password hashing using BCryptPasswordEncoder|$DELIVERED|Ensure passwords are never stored in plain text."
"[BACKEND] Turnstile Captcha verification service|$DELIVERED|Integrate Cloudflare Turnstile for registration security."
"[BACKEND] GameScoreController: GET /scores/{gameId} endpoint|$DELIVERED|Fetch leaderboard for a specific game."
"[BACKEND] GameScoreController: POST /scores/submit endpoint|$DELIVERED|Record user game results."
"[BACKEND] GameLogController: GET /logs/{trainingId} endpoint|$DELIVERED|Retrieve historical training logs."
"[BACKEND] GameLogWebSocketController: WebSocket log streaming|$DELIVERED|Initial setup for real-time log pushing."
"[BACKEND] FileUploadController: Multipart file handling|$DELIVERED|Upload user scripts to local storage."
"[BACKEND] FileDownloadController: Fetching training artifacts|$DELIVERED|Securely serve result files to users."
"[BACKEND] MessageController: GET /messages/inbox endpoint|$DELIVERED|Retrieve user notifications."
"[BACKEND] FriendshipController: POST /friends/request endpoint|$DELIVERED|Send friend requests to other users."
"[BACKEND] FriendshipController: GET /friends/list endpoint|$DELIVERED|List current friends and their online status."
"[BACKEND] UserProgressController: Level and XP calculation logic|$DELIVERED|Calculate user rank based on training success."
"[BACKEND] EmailController: Verification email sending|$DELIVERED|Send tokenized links to new users."
"[BACKEND] CommentsController: GET /comments/{gameId} endpoint|$DELIVERED|Fetch user reviews for a game."
"[BACKEND] CommentsController: POST /comments/add endpoint|$DELIVERED|Allow users to review platform features."
"[BACKEND] DTO Mapping for User responses|$DELIVERED|Prevent sensitive data leakage in API responses."
"[BACKEND] OpenAPI/Swagger documentation integration|$DELIVERED|Setup auto-generated API docs at /swagger-ui."
"[BACKEND] Global Exception Handler for REST errors|$DELIVERED|Consistent error formatting across all endpoints."
"[BACKEND] Validation constraints on User DTOs|$DELIVERED|Add @Email, @NotBlank, and @Size annotations."
"[BACKEND] Logging configuration with Logback|$DELIVERED|Setup file and console logging for production."
"[BACKEND] ProfileModify: PATCH /users/profile endpoint|$DELIVERED|Allow users to update bio and avatar."
"[BACKEND] ForgotPassword: Reset token generation|$DELIVERED|Handle password recovery flow via email."
"[BACKEND] UserDetailsModal: Service for user search|$DELIVERED|Lookup other players by username."
"[BACKEND] BadgePreview: Service for user achievements|$DELIVERED|List earned badges for profile display."
"[BACKEND] FilterDropdown: Dynamic category retrieval|$DELIVERED|Fetch list of games and training types."
"[BACKEND] GameCode: Script validation service|$DELIVERED|Check for basic syntax errors before training."
"[BACKEND] TutorialComponents: Step-by-step progress tracking|$DELIVERED|Save user progress in the onboarding flow."
"[BACKEND] EventModal: Retrieval of active platform events|$DELIVERED|Show current competitions and tournaments."
"[BACKEND] ProtectedRoute: Server-side role verification|$DELIVERED|Restrict admin endpoints to staff."
"[BACKEND] EmailVerificationPopup: Token verification service|$DELIVERED|Finalize email confirmation in DB."
"[BACKEND] MessageNotifications: Real-time alert service|$DELIVERED|Push notifications to connected clients."
"[BACKEND] MultiplayerGame: Matchmaking queue logic|$DELIVERED|Basic pairing of users for games."
"[BACKEND] QuizPassing: Educational module scoring|$DELIVERED|Validate quiz answers and award XP."
"[BACKEND] PasswordSecurity: Policy enforcement service|$DELIVERED|Minimum requirements for user passwords."
"[BACKEND] RegistrationWithCaptcha: Backend verification|$DELIVERED|Ensure Turnstile token is valid."
"[BACKEND] ChatMessaging: Direct message storage|$DELIVERED|Persist private messages between users."
"[BACKEND] SnakeGameFlow: Score aggregation service|$DELIVERED|Process results from snake training."
"[BACKEND] CourseProgression: Lesson completion logic|$DELIVERED|Mark tutorials as finished in DB."
"[BACKEND] GameRanking: Periodic leaderboard updates|$DELIVERED|Recalculate top players every hour."
"[BACKEND] AssetManifest: Static resource mapping|$DELIVERED|Serve icons and images via backend proxy."
"[BACKEND] Newsletter: Subscription management|$DELIVERED|Handle email list for platform updates."
"[BACKEND] Profile: Social link integration|$DELIVERED|Allow users to link GitHub/LinkedIn."

# Delivered - Frontend (50)
"[FRONT] React 18 project initialization|$DELIVERED|Setup project with CRA and TypeScript."
"[FRONT] Material UI theme configuration|$DELIVERED|Customize colors, typography and spacing."
"[FRONT] Tailwind CSS integration|$DELIVERED|Setup utility classes for responsive layouts."
"[FRONT] Axios client with interceptors|$DELIVERED|Handle JWT injection and 401 redirects."
"[FRONT] React Router DOM setup|$DELIVERED|Define core routes and protected paths."
"[FRONT] Landing Page: Responsive hero section|$DELIVERED|Call-to-action and value proposition display."
"[FRONT] Navbar component: Dynamic auth state|$DELIVERED|Show profile/login based on user status."
"[FRONT] Sidebar: Navigation for dashboard|$DELIVERED|Quick access to training, profile, and games."
"[FRONT] Registration Page: Formik and Yup integration|$DELIVERED|Form validation and submission logic."
"[FRONT] Login Page: Persisted session handling|$DELIVERED|Secure storage of JWT in localStorage."
"[FRONT] Profile Page: User stats visualization|$DELIVERED|Graphs for XP growth and win rate."
"[FRONT] All Games Page: Filterable game list|$DELIVERED|Search and category filtering for games."
"[FRONT] Game Page: Integrated code editor (Monaco)|$DELIVERED|Allow users to write scripts in-browser."
"[FRONT] Training Dashboard: Active session cards|$DELIVERED|Monitor multiple AI agents at once."
"[FRONT] Real-time Log Viewer: ANSI to HTML mapping|$DELIVERED|Render terminal output in a web terminal."
"[FRONT] Badge Preview: Grid of user achievements|$DELIVERED|Display locked/unlocked icons for badges."
"[FRONT] Filter Dropdown: Custom MUI select component|$DELIVERED|Reusable dropdown for game categories."
"[FRONT] User Details Modal: Social interaction|$DELIVERED|View other profiles and send friend requests."
"[FRONT] Tutorial Components: Onboarding stepper|$DELIVERED|Guided tour of the platform features."
"[FRONT] File Upload Modal: Drag-and-drop support|$DELIVERED|Easy script submission for users."
"[FRONT] Protected Route: HOC for auth guarding|$DELIVERED|Redirect unauthenticated users to login."
"[FRONT] Event Modal: Active tournament display|$DELIVERED|Show countdowns and registration for events."
"[FRONT] Email Verification Popup: UI feedback|$DELIVERED|Success/error messages for email confirmation."
"[FRONT] Forgot Password: Email submission form|$DELIVERED|Initiate recovery flow from the UI."
"[FRONT] Message Notifications: Toast notifications|$DELIVERED|Real-time alerts for system messages."
"[FRONT] Snake Game Flow: Integrated UI logic|$DELIVERED|Handle start/stop and results for Snake."
"[FRONT] Course Progression: Lesson roadmap UI|$DELIVERED|Visual timeline of educational content."
"[FRONT] Multiplayer Game: Lobby and match UI|$DELIVERED|Wait for opponents and see live scores."
"[FRONT] Password Security: Strength meter component|$DELIVERED|Real-time feedback on password complexity."
"[FRONT] Quiz Passing: Interactive question cards|$DELIVERED|Multiple choice and code snippet quizzes."
"[FRONT] Chat Messaging: Real-time chat interface|$DELIVERED|StompJS integration for direct messaging."
"[FRONT] Contact Page: Support request form|$DELIVERED|Send inquiries to the Lumia team."
"[FRONT] Courses Page: Educational content library|$DELIVERED|List and filter available tutorials."
"[FRONT] Events Page: Full schedule of competitions|$DELIVERED|Calendar view for platform events."
"[FRONT] i18n: Multi-language support (EN/FR)|$DELIVERED|Setup translations for core UI strings."
"[FRONT] Footer: Links and social media|$DELIVERED|Standard footer with legal and contact links."
"[FRONT] Newsletter component: Signup section|$DELIVERED|Integrated subscription form in footer."
"[FRONT] Ranking Players component: Refactored CSS|$DELIVERED|Improved styling for the leaderboard table."
"[FRONT] Ranking Players: Score and username mapping|$DELIVERED|Correctly display player data from API."
"[FRONT] Profile: Fix white screen when not logged in|$DELIVERED|Add null checks and redirects for profile."
"[FRONT] Reviews: Fix white screen when not logged in|$DELIVERED|Handle empty state for user reviews."
"[FRONT] Game Select: Dynamic cats and dogs selection|$DELIVERED|Image recognition game setup logic."
"[FRONT] Connect4: Game UI and logic fix|$DELIVERED|Repair interactive board for Connect4."
"[FRONT] Asset Optimization: Icon compression|$DELIVERED|Reduced SVG bundle size for faster loading."
"[FRONT] Responsive Design: Tablet and Mobile fixes|$DELIVERED|Grid adjustments for small screens."
"[FRONT] Animation: Framer Motion for page transitions|$DELIVERED|Smooth entry/exit for main views."
"[FRONT] Error Boundary: Global fallback UI|$DELIVERED|Catch and report frontend crashes."
"[FRONT] Loading State: Skeleton loaders for profile|$DELIVERED|Better UX during data fetching."
"[FRONT] Dark Mode: MUI Theme switching logic|$DELIVERED|Allow users to toggle between light and dark."
"[FRONT] Typography: Font optimization and sizing|$DELIVERED|Improved readability across all pages."

# Delivered - Infrastructure & Cluster Manager (30)
"[INFRA] Dockerfile for Backend service|$DELIVERED|Multi-stage build for Spring Boot application."
"[INFRA] Dockerfile for Frontend service|$DELIVERED|Nginx configuration for React SPA."
"[INFRA] Docker Compose: Orchestration for dev|$DELIVERED|Setup mongo, back, front, and manager."
"[INFRA] MongoDB Seeding: initial data script|$DELIVERED|Setup test users and games in mongoinit.js."
"[INFRA] Cluster Manager: FastAPI project setup|$DELIVERED|Initialize Python environment and API routes."
"[INFRA] Cluster Manager: Docker API integration|$DELIVERED|Allow manager to spawn worker containers."
"[INFRA] Cluster Manager: Volume mapping for uploads|$DELIVERED|Share scripts between backend and workers."
"[INFRA] Cluster Manager: AI script execution logic|$DELIVERED|Dynamically run user code in isolated envs."
"[INFRA] Cluster Manager: Training log collection|$DELIVERED|Aggregate stdout/stderr from containers."
"[INFRA] Cluster Manager: Result persistence service|$DELIVERED|Save .pt models and final scores."
"[INFRA] Cluster Manager: AI-Vault directory structure|$DELIVERED|Organize scripts by user and game ID."
"[INFRA] Cluster Manager: DeliveringQueue implementation|$DELIVERED|FIFO queue for training requests."
"[INFRA] Cluster Manager: Base Docker images for games|$DELIVERED|Optimized images for Snake and Connect4."
"[INFRA] Cluster Manager: ImageRecognition base image|$DELIVERED|Pytorch and CUDA support for image game."
"[INFRA] Cluster Manager: Resource limiting for containers|$DELIVERED|Restrict CPU and RAM for user scripts."
"[INFRA] Cluster Manager: Health check endpoints|$DELIVERED|Monitor status of the orchestration service."
"[INFRA] VPS: Server hardening and SSH setup|$DELIVERED|Initial cloud instance configuration."
"[INFRA] VPS: Nginx Reverse Proxy configuration|$DELIVERED|Setup SSL and domain routing."
"[INFRA] VPS: Automated backup for MongoDB|$DELIVERED|Nightly dumps to external storage."
"[INFRA] CI/CD: GitHub Actions for build/test|$DELIVERED|Run unit tests on every pull request."
"[INFRA] CI/CD: Automated deployment to VPS|$DELIVERED|Push docker images to registry and restart."
"[INFRA] Monitoring: Docker container stats|$DELIVERED|Basic monitoring of resource usage."
"[INFRA] Logging: Centralized log aggregation|$DELIVERED|Unified view of all service logs."
"[INFRA] Networking: Internal Docker network setup|$DELIVERED|Isolated network for backend communication."
"[INFRA] Secrets: Environment variable management|$DELIVERED|Securely inject API keys and DB passwords."
"[INFRA] Scripts: Lumia.sh startup utility|$DELIVERED|Single script to boot the entire stack."
"[INFRA] Scripts: file_monitor.py for hot-reload|$DELIVERED|Watch for new uploads in the shared volume."
"[INFRA] Scripts: pt_manager.py for model versioning|$DELIVERED|Manage multiple training runs per user."
"[INFRA] Scripts: manage_user.py for cleanup|$DELIVERED|Garbage collection for old training data."
"[INFRA] Documentation: System architecture map|$DELIVERED|Visual diagram of microservices."

# Delivered - Games & AI (30)
"[GAME] Snake Game: Core logic implementation|$DELIVERED|Python implementation of Snake for AI."
"[GAME] Snake Game: State representation for AI|$DELIVERED|Define inputs for the user's brain script."
"[GAME] Snake Game: Scoring and reward function|$DELIVERED|Calculate performance based on length/time."
"[GAME] Connect4: Game engine implementation|$DELIVERED|Robust logic for move validation and win check."
"[GAME] Connect4: Minimax baseline opponent|$DELIVERED|Initial AI for users to test against."
"[GAME] Image Recognition: Dataset preparation|$DELIVERED|Organize cat vs dog images for training."
"[GAME] Image Recognition: Base training script|$DELIVERED|Pytorch boilerplate for user adaptation."
"[GAME] Image Recognition: Evaluation metrics|$DELIVERED|Accuracy and loss calculation logic."
"[GAME] Training Packages: tp-snake structure|$DELIVERED|README and starter script for Snake."
"[GAME] Training Packages: tp-connect4 structure|$DELIVERED|README and starter script for Connect4."
"[GAME] Training Packages: tp-image structure|$DELIVERED|README and starter script for Image Rec."
"[GAME] Starter Scripts: Python template for AI|$DELIVERED|Abstract base class for user scripts."
"[GAME] AI-snake.py: Reference implementation|$DELIVERED|Working example for Snake AI."
"[GAME] AI-connect4.py: Reference implementation|$DELIVERED|Working example for Connect4 AI."
"[GAME] AI-imageRecognition.py: Reference implementation|$DELIVERED|Working example for Image Rec AI."
"[GAME] Game Vault: Versioned game logic storage|$DELIVERED|Keep game engines independent of AI scripts."
"[GAME] SnakeGame.py: Optimized rendering for logs|$DELIVERED|Generate lightweight ASCII frames."
"[GAME] Connect4Game.py: Bitboard implementation|$DELIVERED|Fast performance for intensive training."
"[GAME] ImageRecognitionGame.py: Batch processing|$DELIVERED|Efficient data loading for training."
"[GAME] selection.py: Dynamic game picker logic|$DELIVERED|Allow manager to switch between game engines."
"[GAME] init.sh: Game environment setup script|$DELIVERED|Install dependencies inside the worker."
"[GAME] run-game.sh: Wrapper for AI execution|$DELIVERED|Handle timeouts and error reporting."
"[GAME] Game-Vault: Asset management for games|$DELIVERED|Sprites and sounds for game visualization."
"[GAME] AI Logic: Abstracting state from environment|$DELIVERED|Clean interface for AI scripting."
"[GAME] AI Logic: Normalization of sensor inputs|$DELIVERED|Helpful utilities for neural networks."
"[GAME] AI Logic: Support for Reinforcement Learning|$DELIVERED|Hooks for reward-based training."
"[GAME] AI Logic: Support for Supervised Learning|$DELIVERED|Data loaders for labeled datasets."
"[GAME] Debugging: debugdocker.py for local testing|$DELIVERED|Manually trigger training in Docker."
"[GAME] Documentation: AI scripting guide|$DELIVERED|Comprehensive manual for writing agents."
"[GAME] Examples: Catalog of common AI patterns|$DELIVERED|Search, Q-Learning, and CNN examples."

# In Progress (15)
"[BACKEND] Achievement system: Logic and DB schema|$IN_PROGRESS|Implementing criteria for unlocking badges."
"[BACKEND] Real-time Log Streaming via WebSockets|$IN_PROGRESS|Integrating STOMP for live training output."
"[FRONT] Achievement Dashboard: Visual progress UI|$IN_PROGRESS|Show unlocked badges and current goals."
"[FRONT] Interactive Training Charts: Live metrics|$IN_PROGRESS|Recharts integration for loss/accuracy."
"[INFRA] Cluster Manager: Resource monitoring API|$IN_PROGRESS|Expose CPU/RAM usage per training session."
"[GAME] Image Recognition: Enhanced dataset expansion|$IN_PROGRESS|Adding more categories (Bird, Car, etc.)."
"[TEST] E2E: Full User Journey integration tests|$IN_PROGRESS|Cypress scenarios for register -> train -> win."
"[BACKEND] Multiplayer: Competitive matchmaking logic|$IN_PROGRESS|Ranking-based pairing for live games."
"[FRONT] Social: Direct messaging improvements|$IN_PROGRESS|Threaded chat and read receipts."
"[INFRA] VPS: Integration of Prometheus/Grafana|$IN_PROGRESS|Dashboard for system health and load."
"[BACKEND] Search: Optimized user and game indexing|$IN_PROGRESS|Speed up global search functionality."
"[FRONT] UI Polish: Animation and micro-interactions|$IN_PROGRESS|Improving responsiveness and feel."
"[GAME] Connect4: Advanced AI opponent with MCTS|$IN_PROGRESS|Providing a harder challenge for pro users."
"[TEST] Backend: Unit test coverage for Security layer|$IN_PROGRESS|Ensuring 100% coverage on auth logic."
"[BACKEND] Notification System: Browser Push support|$IN_PROGRESS|Enable notifications when training finishes."

# Code Review (10)
"[BACKEND] Global Leaderboard: Optimization for scale|$CODE_REVIEW|Caching top ranks to reduce DB load."
"[BACKEND] File Upload: Virus scanning and isolation|$CODE_REVIEW|Enhancing security for user submissions."
"[INFRA] Docker: Migration to Rootless mode|$CODE_REVIEW|Improving security for container execution."
"[FRONT] Form Validation: Enhanced error reporting|$CODE_REVIEW|Clearer feedback for complex form errors."
"[BACKEND] API: Bulk retrieval for friend status|$CODE_REVIEW|Reducing roundtrips for social sidebar."
"[GAME] Snake: Physics engine refinement|$CODE_REVIEW|Fixing edge cases in collision detection."
"[FRONT] State: Migration to Redux Toolkit|$CODE_REVIEW|Refactoring global state for better debuggability."
"[INFRA] VPS: Automated SSL renewal script|$CODE_REVIEW|Certbot integration for Let's Encrypt."
"[BACKEND] Documentation: Complete Javadoc generation|$CODE_REVIEW|Ensuring all services are documented."
"[FRONT] Accessibility: Focus management for modals|$CODE_REVIEW|Correcting tab order in popups."

# Todo (15)
"[BACKEND] Subscription: Stripe integration for Premium|$TODO|Payment processing for higher training limits."
"[FRONT] Dark Mode: Persistent user preference|$TODO|Save theme choice in DB/localStorage."
"[BACKEND] API: Historical ranking snapshots|$TODO|Track leaderboard changes over time."
"[INFRA] Monitoring: Automated alert system|$TODO|Slack/Email alerts for service downtime."
"[BACKEND] Localization: Support for ES/DE/IT|$TODO|Expanding multi-language capabilities."
"[FRONT] SEO: Meta tags and social sharing optimization|$TODO|Better visibility on search engines."
"[BACKEND] Cleanup: Automated data retention policy|$TODO|Delete very old logs and temp files."
"[INFRA] Scalability: Load balancing for Cluster Manager|$TODO|Distribute training across multiple VPS."
"[GAME] Image Recognition: Transfer learning support|$TODO|Allow users to use pre-trained weights."
"[FRONT] Mobile: Dedicated PWA configuration|$TODO|Improve home-screen install experience."
"[TEST] Performance: Load testing for API endpoints|$TODO|Verify system behavior under high traffic."
"[BACKEND] Audit: User activity logging|$TODO|Track administrative actions for security."
"[FRONT] Feedback: In-app bug reporting tool|$TODO|Allow users to submit issues directly."
"[BACKEND] OAuth: Integration with Discord/Google|$TODO|Expanding social login options."
"[ARCH] Service Discovery: Consul/Eureka integration|$TODO|Manage microservice addresses dynamically."
)

for task in "${tasks[@]}"; do
  IFS="|" read -r TITLE STATUS_ID BODY <<< "$task"
  create_task "$TITLE" "$STATUS_ID" "$BODY"
done

