import { coursesDataFr } from './CoursesDataFR';
import { coursesDataEn } from './CoursesDataEN';
import { formationCheckpointsFr, formationCheckpointsEn } from '../components/FormationCheckpoints';

export const formationsFrData = [
	{
		id: 0,
		name: "Parcours facile",
		difficulty: "Facile",
		image: "https://i.imgur.com/1QphHhP.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataFr[0],
			coursesDataFr[1],
			coursesDataFr[2],
			coursesDataFr[3],
			coursesDataFr[4],
			coursesDataFr[5],
			coursesDataFr[6],
			coursesDataFr[7],
			coursesDataFr[8],
			coursesDataFr[9],
			{ ...formationCheckpointsFr[0][0], type: 'quiz' },
			coursesDataFr[10],
			coursesDataFr[11],
			coursesDataFr[12],
			coursesDataFr[13],
			coursesDataFr[14],
			coursesDataFr[15],
			coursesDataFr[16],
			coursesDataFr[17],
			coursesDataFr[18],
			coursesDataFr[19],
			{ ...formationCheckpointsFr[0][1], type: 'quiz' },
			coursesDataFr[20],
			coursesDataFr[21],
			coursesDataFr[22],
			coursesDataFr[23],
			coursesDataFr[24],
			coursesDataFr[25],
			coursesDataFr[26],
			coursesDataFr[27],
			{ ...formationCheckpointsFr[0][2], type: 'quiz' },
		],
		completed: true,
	},
	{
		id: 1,
		name: "Parcours Intermediaire",
		difficulty: "Intermediaire",
		image: "https://i.imgur.com/3PpsvED.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataFr[28],
			coursesDataFr[29],
			coursesDataFr[30],
			coursesDataFr[31],
			{ ...formationCheckpointsFr[1][0], type: 'quiz' },
			coursesDataFr[32],
			coursesDataFr[33],
			coursesDataFr[34],
			coursesDataFr[35],
			{ ...formationCheckpointsFr[1][1], type: 'quiz' },
			coursesDataFr[36],
			coursesDataFr[37],
		],
		completed: false,
	},
	{
		id: 2,
		name: "Parcours expert",
		difficulty: "Expert",
		image: "https://i.imgur.com/cFvtZru.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataFr[38],
			coursesDataFr[39],
			coursesDataFr[40],
			coursesDataFr[41],
			coursesDataFr[42],
			coursesDataFr[43],
		],
		completed: false,
	}
]

export const formationsEnData = [
	{
		id: 0,
		name: "Easy Path",
		difficulty: "Easy",
		image: "https://i.imgur.com/1QphHhP.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataEn[0],
			coursesDataEn[1],
			coursesDataEn[2],
			coursesDataEn[3],
			coursesDataEn[4],
			coursesDataEn[5],
			coursesDataEn[6],
			coursesDataEn[7],
			coursesDataEn[8],
			coursesDataEn[9],
			{ ...formationCheckpointsEn[0][0], type: 'quiz' },
			coursesDataEn[10],
			coursesDataEn[11],
			coursesDataEn[12],
			coursesDataEn[13],
			coursesDataEn[14],
			coursesDataEn[15],
			coursesDataEn[16],
			coursesDataEn[17],
			coursesDataEn[18],
			coursesDataEn[19],
			{ ...formationCheckpointsEn[0][1], type: 'quiz' },
			coursesDataEn[20],
			coursesDataEn[21],
			coursesDataEn[22],
			coursesDataEn[23],
			coursesDataEn[24],
			coursesDataEn[25],
			coursesDataEn[26],
			coursesDataEn[27],
			{ ...formationCheckpointsEn[0][2], type: 'quiz' },
		],
		completed: true,
	},
	{
		id: 1,
		name: "Medium Path",
		difficulty: "Medium",
		image: "https://i.imgur.com/3PpsvED.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataEn[28],
			coursesDataEn[29],
			coursesDataEn[30],
			coursesDataEn[31],
			{ ...formationCheckpointsEn[1][0], type: 'quiz' },
			coursesDataEn[32],
			coursesDataEn[33],
			coursesDataEn[34],
			coursesDataEn[35],
			{ ...formationCheckpointsEn[1][1], type: 'quiz' },
			coursesDataEn[36],
			coursesDataEn[37],
		],
		completed: false,
	},
	{
		id: 2,
		name: "Expert Path",
		difficulty: "Expert",
		image: "https://i.imgur.com/cFvtZru.png",
		locked: false,
		isFree: true,
		content: [
			coursesDataEn[38],
			coursesDataEn[39],
			coursesDataEn[40],
			{ ...formationCheckpointsEn[2][0], type: 'quiz' },
			coursesDataEn[41],
			coursesDataEn[42],
			coursesDataEn[43],
		],
		completed: false,
	}
]
