package com.example.demo;

public enum EventName {
    OPEN_BETA_LUMIA_AI,
    AI_WORKSHOP_NEURAL_NETWORKS,
    HACKATHON_AI_INNOVATION,
    WEBINAR_MACHINE_LEARNING,
    NETWORKING_TECH_MEETUP,
    COMPETITION_CODE_CHALLENGE
}
